In [45]:
import urllib.request
from bs4 import BeautifulSoup
from janome.tokenizer import Tokenizer
from sudachipy import tokenizer
from sudachipy import dictionary
import pykakasi
import pandas as pd

def opnfile(link,oppath):
    urllib.request.urlretrieve(link,oppath)
  
    file = open(oppath, "r")
    contents = file.read()
    soup = BeautifulSoup(contents, 'html.parser')
    
    f = open("test1.txt", "w")
  
    # traverse paragraphs from soup
    for data in soup.find_all("p"):
        sum = data.get_text()
        f.writelines(sum)
  
    f.close()
    file.close()
    
def tknizer():  
    t = Tokenizer()
    f1 = open("test1.txt", "r")
    ct= f1.read()
    f2 = open("test2.txt", "w")

    punctuations = '''。.、　』『］・「」!()-[]{};:'"\,<>./?@#$%^&*_！~～）（？）…◆でが　です　よねも　だ　て　に　は　な　と し　の　ん　を １　２　３　４　５　６　７　８　９　'''
    alpha='''1234567890'''
    for token in t.tokenize(ct, wakati=True):
        if token not in punctuations and alpha:
            f2.writelines(token)
    print("tokenized")
            
    f2.close()
    f1.close()

def dbltknz_list():
    tokenizer_obj = dictionary.Dictionary().create()
    mode = tokenizer.Tokenizer.SplitMode.C
    f3 = open("test2.txt", "r")
    ct2= f3.read()

    list1=[m.dictionary_form() for m in tokenizer_obj.tokenize(ct2, mode='utf8')] 
    f3.close()
    test_list = set(list1)
    res=[]
    for k in test_list:
        res.append(k)
    print("converted to list")
    return res

def imi(res):
    kks = pykakasi.kakasi()
    result1=[]
    orig =[]
    kana =[]
    hira =[]
    romaji =[]
    for k in res:
        result=kks.convert(k)
        for item in result:
            result1.append(result)
        
            orig.append(item['orig'])
            kana.append(item['kana'])
            hira.append(item['hira'])
            if (item['hepburn']==' '):
                romaji.append("NULL")
            else:romaji.append(item['hepburn'])
        #print("{}: kana '{}', hiragana '{}', romaji: '{}'".format(item['orig'], item['kana'], item['hira'], item['hepburn'])) 
    data = {'Orig': orig,
        'kana':kana,
        'hira':hira,
        'romaji':romaji}
    df = pd.DataFrame(data)
    print("Data frame created")
    return df

def to_xl(df,xl_op):
    df.to_excel(xl_op)  
    print("Excel created")

#link="https://www.sokanet.jp/creatio/denji-2/"
link=input()
oppath="text_file.txt"
excelop='output.xlsx'
opnfile(link,oppath)
tknizer()
rtt=dbltknz_list()
dff=imi(rtt)
to_xl(dff,excelop)

 https://www.sokanet.jp/creatio/staff-4/?archive_type=category

tokenized
converted to list
Data frame created
Excel created

In [39]:
dff.tail()

    Orig  kana  hira  romaji
140   使命   シメイ   しめい  shimei
141   ぱっ    パッ    ぱっ   patsu
142   全部   ゼンブ   ぜんぶ   zenbu
143   仏法  ブッポウ  ぶっぽう  buppou
144    桜   サクラ   さくら  sakura